CREATE USER "OCI_FOCUS_REPORTS" DEFAULT COLLATION "USING_NLS_COMP" 
   DEFAULT TABLESPACE "DATA"
   TEMPORARY TABLESPACE "TEMP";
ALTER USER "OCI_FOCUS_REPORTS" QUOTA UNLIMITED ON "DATA";
GRANT "CONNECT" TO "OCI_FOCUS_REPORTS";
GRANT "RESOURCE" TO "OCI_FOCUS_REPORTS";
GRANT "DATAPUMP_CLOUD_EXP" TO "OCI_FOCUS_REPORTS";
GRANT "DATAPUMP_CLOUD_IMP" TO "OCI_FOCUS_REPORTS";
GRANT "DWROLE" TO "OCI_FOCUS_REPORTS";
GRANT "CONSOLE_DEVELOPER" TO "OCI_FOCUS_REPORTS";
GRANT "OML_DEVELOPER" TO "OCI_FOCUS_REPORTS";
GRANT EXECUTE ON "DBMS_CLOUD_PIPELINE" TO "OCI_FOCUS_REPORTS";
GRANT EXECUTE ON "DBMS_CLOUD_AI" TO "OCI_FOCUS_REPORTS";
GRANT EXECUTE ON "ADMIN"."OCI$RESOURCE_PRINCIPAL" TO "OCI_FOCUS_REPORTS";
ALTER USER "OCI_FOCUS_REPORTS" DEFAULT ROLE "DWROLE", "CONSOLE_DEVELOPER", "OML_DEVELOPER";
ALTER PROFILE "DEFAULT"
    LIMIT 
         PASSWORD_LIFE_TIME UNLIMITED;
