CREATE USER "USAGE" DEFAULT COLLATION "USING_NLS_COMP" 
   DEFAULT TABLESPACE "DATA"
   TEMPORARY TABLESPACE "TEMP";
ALTER USER "USAGE" QUOTA UNLIMITED ON "DATA";
GRANT "CONNECT" TO "USAGE";
GRANT "RESOURCE" TO "USAGE";
GRANT "DATAPUMP_CLOUD_EXP" TO "USAGE";
GRANT "DATAPUMP_CLOUD_IMP" TO "USAGE";
GRANT "DWROLE" TO "USAGE";
GRANT "CONSOLE_DEVELOPER" TO "USAGE";
GRANT "OML_DEVELOPER" TO "USAGE";
GRANT EXECUTE ON "DBMS_CLOUD_PIPELINE" TO "USAGE";
GRANT EXECUTE ON "DBMS_CLOUD_AI" TO "USAGE";
GRANT EXECUTE ON "ADMIN"."OCI$RESOURCE_PRINCIPAL" TO "USAGE";
ALTER USER "USAGE" DEFAULT ROLE "DWROLE", "CONSOLE_DEVELOPER", "OML_DEVELOPER";
ALTER PROFILE "DEFAULT"
    LIMIT 
         PASSWORD_LIFE_TIME UNLIMITED;
