CREATE TABLE OCI_AVAILABILITY_METRICS_PY
(
    RESOURCEDISPLAYNAME VARCHAR2(64),
    TIMESTAMP           TIMESTAMP WITH TIME ZONE NOT NULL,
    NAMESPACE           VARCHAR2(64),
    COMPARTMENT_ID      VARCHAR2(256),
    VALUE               NUMBER,
    METRIC_NAME         VARCHAR2(128)
)
TABLESPACE DATA
    PARTITION BY RANGE ("TIMESTAMP")
        INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
        (
        PARTITION p_initial VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD'))
);