CREATE TABLE OCI_FOCUS_REPORTS.OCI_EXA_MAINTENANCE_PY 
    ( 
     ID                                       VARCHAR2 (1000) , 
     COMPARTMENT_ID                           VARCHAR2 (1000) , 
     CURRENT_CUSTOM_ACTION_TIMEOUT_IN_MINS    NUMBER , 
     CURRENT_PATCHING_COMPONENT               VARCHAR2 (1000) , 
     CUSTOM_ACTION_TIMEOUT_IN_MINS            NUMBER , 
     DATABASE_SOFTWARE_IMAGE_ID               VARCHAR2 (1000) , 
     DESCRIPTION                              VARCHAR2 (10000) , 
     DISPLAY_NAME                             VARCHAR2 (500) , 
     ESTIMATED_DB_SERVER_PATCHING_TIME        NUMBER , 
     ESTIMATED_NETWORK_SWITCHES_PATCHING_TIME NUMBER , 
     ESTIMATED_STORAGE_SERVER_PATCHING_TIME   NUMBER , 
     TOTAL_ESTIMATED_PATCHING_TIME            NUMBER , 
     IS_CUSTOM_ACTION_TIMEOUT_ENABLED         VARCHAR2 (10) , 
     IS_DST_FILE_UPDATE_ENABLED               VARCHAR2 (10) , 
     IS_MAINTENANCE_RUN_GRANULAR              VARCHAR2 (10) , 
     LIFECYCLE_DETAILS                        VARCHAR2 (10000) , 
     LIFECYCLE_STATE                          VARCHAR2 (50) , 
     MAINTENANCE_SUBTYPE                      VARCHAR2 (1000) , 
     MAINTENANCE_TYPE                         VARCHAR2 (1000) , 
     PATCH_FAILURE_COUNT                      NUMBER , 
     PATCH_ID                                 VARCHAR2 (50) , 
     PATCHING_END_TIME                        TIMESTAMP , 
     PATCHING_MODE                            VARCHAR2 (50) , 
     PATCHING_START_TIME                      TIMESTAMP , 
     PATCHING_STATUS                          VARCHAR2 (50) , 
     PEER_MAINTENANCE_RUN_ID                  VARCHAR2 (1000) , 
     PEER_MAINTENANCE_RUN_IDS                 CLOB , 
     TARGET_DB_SERVER_VERSION                 VARCHAR2 (1000) , 
     TARGET_RESOURCE_ID                       VARCHAR2 (200) , 
     TARGET_RESOURCE_TYPE                     VARCHAR2 (1000) , 
     TARGET_STORAGE_SERVER_VERSION            VARCHAR2 (1000) , 
     TIME_ENDED                               TIMESTAMP , 
     TIME_SCHEDULED                           TIMESTAMP , 
     TIME_STARTED                             TIMESTAMP , 
     TOTAL_TIME_TAKEN_IN_MINS                 NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;