CREATE TABLE OCI_FOCUS_REPORTS.OCI_RESOURCES_PY 
    ( 
     DISPLAY_NAME VARCHAR2 (1000) , 
     IDENTIFIER   VARCHAR2 (1000) , 
     REGION       VARCHAR2 (60) 
    ) 
    TABLESPACE DATA 
    LOGGING 
;