DROP MATERIALIZED VIEW USAGE.RATECARD_MV PRESERVE TABLE 
;
DROP TABLE USAGE.RATECARD_MV CASCADE CONSTRAINTS 
;
CREATE MATERIALIZED VIEW USAGE.RATECARD_MV ( CHARGEDESCRIPTION , PRICINGUNIT , SKUID , ACTUALUNITPRICE , LISTUNITPRICE ) 
    TABLESPACE DATA 
    LOGGING 
    USING INDEX 
    REFRESH COMPLETE ON DEMAND 
    START WITH TO_DATE('2025-05-06','YYYY-MM-DD') 
    NEXT TO_DATE('(TRUNC(SYSTIMESTAMP) + INTERVAL '1' DAY)', 'YYYY-MM-DD') 
    USING ENFORCED CONSTRAINTS 
        USING DEFAULT ROLLBACK SEGMENT 
    AS SELECT 
    CHARGEDESCRIPTION, 
    PRICINGUNIT,
    MIN(SKUID) AS SKUID, 
    AVG(ROUND(EFFECTIVECOST/PRICINGQUANTITY, 4)) AS ACTUALUNITPRICE, 
    MAX(LISTUNITPRICE) AS LISTUNITPRICE
FROM 
    FOCUS_REPORTS_PY
WHERE 
    PRICINGQUANTITY > 0
AND CHARGEDESCRIPTION NOT LIKE UPPER('%FREE%')
AND BILLINGACCOUNTID='9379274'
AND CHARGECATEGORY='Usage'
GROUP BY 
    BILLINGACCOUNTID, 
    CHARGEDESCRIPTION, 
    PRICINGUNIT 
;
COMMENT ON MATERIALIZED VIEW USAGE.RATECARD_MV IS 'snapshot table for snapshot USAGE.RATECARD_MV'
;