DROP MATERIALIZED VIEW OCI_FOCUS_REPORTS.RATECARD_MV PRESERVE TABLE;
DROP TABLE OCI_FOCUS_REPORTS.RATECARD_MV CASCADE CONSTRAINTS;
CREATE MATERIALIZED VIEW OCI_FOCUS_REPORTS.RATECARD_MV ( CHARGEDESCRIPTION , PRICINGUNIT , SKUID , ACTUALUNITPRICE , LISTUNITPRICE ) 
    REFRESH FORCE START WITH SYSDATE  
    NEXT (SYSDATE + 1) WITH ROWID
    AS SELECT 
    CHARGEDESCRIPTION, 
    PRICINGUNIT,
    MIN(SKUID) AS SKUID, 
    AVG(ROUND(EFFECTIVECOST/PRICINGQUANTITY, 4)) AS ACTUALUNITPRICE, 
    MAX(LISTUNITPRICE) AS LISTUNITPRICE
FROM 
    OCI_FOCUS_REPORTS.FOCUS_REPORTS_PY
WHERE 
    PRICINGQUANTITY > 0
AND CHARGEDESCRIPTION NOT LIKE UPPER('%FREE%')
AND BILLINGACCOUNTID='9379274'
AND CHARGECATEGORY='Usage'
GROUP BY 
    BILLINGACCOUNTID, 
    CHARGEDESCRIPTION, 
    PRICINGUNIT 
;
COMMENT ON MATERIALIZED VIEW OCI_FOCUS_REPORTS.RATECARD_MV IS 'snapshot table for snapshot OCI_FOCUS_REPORTS.RATECARD_MV'
;