CREATE OR REPLACE VIEW OCI_COST_USAGE_MONTHLY_V AS
SELECT 
    TRUNC(f.BILLINGPERIODSTART, 'MM') AS PERIODSTART,
    f.BILLINGACCOUNTID,
    SUM(f.EFFECTIVECOST) AS TOTAL_COST,
    SUM(f.USAGEQUANTITY) AS TOTAL_USAGE,
    f.USAGEUNIT,
    f.SERVICECATEGORY,
    f.SERVICENAME,
    r.DISPLAY_NAME AS RESOURCE_NAME,
    f.RESOURCETYPE,
    f.CHARGEDESCRIPTION,
    c."Name" AS COMPARTMENT_NAME,
    c."Path" AS COMPARTMENT_PATH
FROM 
    FOCUS_REPORTS_PY f
LEFT JOIN 
    OCI_RESOURCES_PY r 
    ON f.RESOURCEID = r.IDENTIFIER 
LEFT JOIN
    OCI_COMPARTMENTS_PY c
    ON f.OCI_COMPARTMENTID = c."Compartment_ID"
WHERE f.BILLINGPERIODSTART >= TRUNC(ADD_MONTHS(SYSDATE, -6), 'MM')
GROUP BY 
    TRUNC(f.BILLINGPERIODSTART, 'MM'),
    f.BILLINGACCOUNTID,
    f.USAGEUNIT,
    f.SERVICECATEGORY,
    f.SERVICENAME,
    f.RESOURCETYPE,
    f.CHARGEDESCRIPTION,
    r.DISPLAY_NAME,
    c."Name",
    c."Path"
ORDER BY TRUNC(f.BILLINGPERIODSTART, 'MM') DESC;
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.PERIOSTART IS 'Billing period start date (truncated to month)';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.BILLINGACCOUNTID IS 'Unique identifier for the OCI billing account';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.TOTAL_COST IS 'Total effective cost incurred in the billing period';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.TOTAL_USAGE IS 'Total quantity of resource usage in the billing period';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.USAGEUNIT IS 'Unit of measurement for resource usage (e.g., hours, GB)';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.SERVICECATEGORY IS 'High-level category of the OCI service used';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.SERVICENAME IS 'Specific name of the OCI service used';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.RESOURCE_NAME IS 'Human-readable name of the OCI resource';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.RESOURCETYPE IS 'Type of OCI resource (e.g., Compute Instance, Block Volume)';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.CHARGEDESCRIPTION IS 'Description of the charge applied';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.COMPARTMENT_NAME IS 'Name of the OCI compartment where the resource resides';
COMMENT ON COLUMN OCI_COST_USAGE_MONTHLY_V.COMPARTMENT_PATH IS 'Full path of the compartment hierarchy in OCI';
